local Config = {
	Entry17 = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "ENTRY NUMBER SEVENTEEN",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "DARK DARKER YET DARKER",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "THE DARKNESS KEEPS GROWING",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "THE SHADOWS CUTTING DEEPER",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "PHOTON READINGS NEGATIVE",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "THIS NEXT EXPERIMENT",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "SEEMS",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "VERY",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "VERY",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "INTERESTING",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
	},
	RiverPerson = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* ...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 1.5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Tra la la...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 1.5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Beware of the man who speaks in hands.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 2.5,
		},
	},
	RiverPerson2 = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* ...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 1.5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Tra la la...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 1.5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Beware of the man who came from the other world.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 2.5,
		},
	},
	Follower = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* I understand why ASGORE waited so long to hire a new Royal Scientist.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* The previous one... Dr. ______.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* His brilliance was irreplaceable..",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* However, his life... Was cut short.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* One day, his experiments went wrong, and...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
	},
	Follower2 = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* I understand why ASGORE waited so long to hire a new Royal Scientist.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* After all, the old one... Dr. ______. What an act to follow!",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* They say he created the CORE.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* However, his life... Was cut short.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* One day, he fell into his creation, and...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Will Alphys end up the same way?",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
	},
	Follower3 = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Alphys might work faster. But the old Royal Scientist, Doctor _._. ______?",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* One day, he vanished without a trace.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* They say he shattered across time and space.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Ha ha... How can I say so without fear?",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* I'm holding a piece of him right here.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
	},
	GonerKid1 = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Have you ever thought about a world where everything is exactly the same...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Except you don't exist?",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Everything functions perfectly without you...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Ha, ha... The thought terrifies me.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* ...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
	},
	GonerKid2 = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* An umbrella...? But it's not raining.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Ha, ha...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* You know, that does make me feel a little better about this.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Thank you.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Please forget about me.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Please don't think about this anymore.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = .5,
		},
	},
	Warning = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* You know...",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 1,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* it's rude to talk about someone who's listening.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 2,
		},
	},
	Hello = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Hello..?",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 1,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Is anyone there?",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 2,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Its.. so dark.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 2,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "* Please... help me anyone.",
			["Speed"] = .04,
			["Speech"] = script.Narraitor,
			["Persist"] = 2,
		},
	},
	Anomaly = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "(DID/DO/WILL) YOU NOT UNDERSTAND?",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "YOU (WERE/ARE/WILL BE) A THREAT TO US ALL.",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "YOU (WERE/ARE/WILL BE) A ANOMALY.",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
	},
	Purity = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "You put on a innocent facade.",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "You were able to trick them all...",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "But how can you trick the man who's always watching..?",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
	},
	IKnowWhatYouDid = {
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "I can see your sins...",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "They crawl all over you...",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "I know everything you will and have done.",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
		{
			["Label"] = script.Parent.Parent.Parent.TextLabel,
			["Dialog"] = "I see your hands... they are stained in blood.",
			["Speed"] = .07,
			["RanSpeech"] = script.Txt:GetChildren(),
			["Persist"] = .5,
		},
	},
}

return Config
