local Config = {
	["DialogPackets"] = {
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* It's happening again...",
			SpeechAudio = script.Txt,
			Speed = .1,
			Persist = 1,
			CustomLabel = script.EvilLetter,
				Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
				BobbleY = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
			},
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* The feeling of power...",
			SpeechAudio = script.Txt,
			Speed = .1,
			Persist = 1,
			CustomLabel = script.EvilLetter,
			Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
				BobbleY = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
			},
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* It's crawling back into my veins..",
			SpeechAudio = script.Txt,
			Speed = .1,
			Persist = 1,
			CustomLabel = script.EvilLetter,
			Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
				BobbleY = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
			},
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* I didn't ask for this.. But maybe... I never let it go.",
			SpeechAudio = script.Txt,
			Speed = .1,
			Persist = 1,
			CustomLabel = script.EvilLetter,
			Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
				BobbleY = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
			},
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* You're remembering, aren't you?",
			SpeechAudio = script.FloweyVoice,
			Speed = .1,
			Persist = 1,
			CustomLabel = script.NarratorLetter,
			Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
				BobbleY = {Min = 10, Max = 15, Min2= .01, Max2 = .02},
			},
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* No... I'm not like them...",
			SpeechAudio = script.Txt,
			Speed = .1,
			Persist = 1,
			CustomLabel = script.EvilLetter,
			Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 25, Max = 30, Min2= .01, Max2 = .02},
				BobbleY = {Min = 25, Max = 30, Min2= .01, Max2 = .02},
			},
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* But you wanted this.",
			SpeechAudio = script.FloweyVoice,
			Speed = .1,
			Persist = 1,
			CustomLabel = script.NarratorLetter,
			Effects = {"FadeIn"},
		
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* The LOVE",
			SpeechAudio = script.FloweyVoice,
			Speed = .03,
			Persist = 1,
			CustomLabel = script.NarratorLetter,
			Effects = {"FadeIn"},

		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* The strength",
			SpeechAudio = script.FloweyVoice,
			Speed = .03,
			Persist = 1,
			CustomLabel = script.NarratorLetter,
			Effects = {"FadeIn"},

		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* Enough.",
			SpeechAudio = script.Txt,
			Speed = .1,
			Persist = 1,
			CustomLabel = script.EvilLetter,
			Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 55, Max = 60, Min2= .01, Max2 = .02},
				BobbleY = {Min = 55, Max = 60, Min2= .01, Max2 = .02},
			},
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* I'll use this power...",
			SpeechAudio = script.Txt,
			Speed = .05,
			Persist = 1,
			CustomLabel = script.EvilLetter,
			Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 55, Max = 60, Min2= .01, Max2 = .02},
				BobbleY = {Min = 55, Max = 60, Min2= .01, Max2 = .02},
			},
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = "* MY WAY",
			SpeechAudio = script.Txt,
			Speed = .2,
			Persist = 1,
			CustomLabel = script.EvilLetter,
			Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 85, Max = 90, Min2= .01, Max2 = .02},
				BobbleY = {Min = 85, Max = 90, Min2= .01, Max2 = .02},
			},
		},
		{
			ParentGui = script.Parent.Parent.DialogFrame,
			Dialog = " ",
			SpeechAudio = script.FloweyLaugh,
			Speed = .2,
			Persist = 1,
			CustomLabel = script.EvilLetter,
			Effects = {"CustomShake", "FadeIn"},
			CustomShake = {
				BobbleX = {Min = 85, Max = 90, Min2= .01, Max2 = .02},
				BobbleY = {Min = 85, Max = 90, Min2= .01, Max2 = .02},
			},
		},
	},
}

return Config